<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Linh Pham and Jason Lerch">
<meta name="dcterms.date" content="2025-07-30">
<meta name="description" content="How RMINC projects and visualizes results using a sample cross-sectional comparison.">

<title>Under the hood: visualizations in RMINC – digressions on (mouse) brain imaging</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-K98RZYWMVC"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-K98RZYWMVC', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">digressions on (mouse) brain imaging</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jasonlerch/blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Under the hood: visualizations in RMINC</h1>
                  <div>
        <div class="description">
          How RMINC projects and visualizes results using a sample cross-sectional comparison.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">RMINC</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Linh Pham and Jason Lerch </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 30, 2025</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">July 30, 2025</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>RMINC visualization tools are versatile, but how the results are visualized are not super obvious. Here, I’m demonstrating a little bit of what’s happening under the hood using Four Core Genotype rat data that Myrto Lavda had gathered.</p>
<p>Myrto had surgically induced strokes on some of these animals to understand how sex hormones and chromosomes impact stroke outcomes in the brain. We will be comparing the difference in volume between rats of different genotypes and stages of the stroke experiment.</p>
<section id="set-up" class="level1">
<h1>Set up</h1>
<p>Reading in necessary packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>packages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"RMINC"</span>, <span class="st">"MRIcrotome"</span>, <span class="st">"broom"</span>, <span class="st">"forcats"</span>, <span class="st">"gridExtra"</span>, <span class="st">"lspline"</span>, <span class="st">"emmeans"</span>, <span class="st">"png"</span>, <span class="st">"Cairo"</span>, <span class="st">"ggplot2"</span>, <span class="st">"rstatix"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">sapply</span>(packages, <span class="cf">function</span>(x) <span class="fu">library</span>(x, <span class="at">character.only =</span> <span class="cn">TRUE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors

Attaching package: 'MRIcrotome'


The following object is masked from 'package:graphics':

    legend



Attaching package: 'gridExtra'


The following object is masked from 'package:dplyr':

    combine


Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'


Attaching package: 'rstatix'


The following object is masked from 'package:stats':

    filter</code></pre>
</div>
</div>
</section>
<section id="reading-in-the-data" class="level1">
<h1>Reading in the data</h1>
<p>The output of a PydPiper pipeline includes different types of Jacobian determinants for each image. The full Jacobian (log_full_det) is used when one’s interested in volumetric effects and not accounting for total brain volume (TBV). Nonlinear Jacobian (log_nlin_det) is used when TBV should be accounted.</p>
<p>PydPiper saves these determinants after different levels of blurring have been applied to them at each voxel. A FWHM blur of 0.2 is usually used when the analyses are at the voxel level. FWHM of 0 (no blurring) is used when analyses are done at the regional level (since noise from voxel-wise determinants can be reduced when the voxels determinants are averaged/combined to make a regional volume).</p>
<p>The code below reads in a csv, produced from PydPiper pipeline, that indicates where the determinant files for each image/animal are located. Files with FWHM 0.2 are chosen because analyses will be done at the voxel level. Some text manipulations are done to animal ID and time point for ease of analyses later on. A new variable, ‘stage’, is made to determine if the animal was scanned at baseline, after acute stroke, or doing recovery using their file names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pipeout <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/well/lerch/users/dqp841/FCG_Rat_Stroke/pipelines/analysis.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(fwhm<span class="sc">==</span><span class="fl">0.2</span>)<span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Animal.ID =</span> <span class="fu">basename</span>(log_nlin_det), <span class="co"># the following lines are modifying animal IDs and category to make them suitable for subsequent analyses </span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Animal.ID =</span> <span class="fu">str_replace</span>(Animal.ID, <span class="st">"RNC4"</span>, <span class="st">"RNEC4"</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Animal.ID =</span> <span class="fu">str_replace</span>(Animal.ID, <span class="st">"RNEC4_1_Base"</span>, <span class="st">"RNEC4_1c_Base"</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">Animal.ID =</span> <span class="fu">str_replace</span>(Animal.ID, <span class="st">"RNEC1_1b"</span>, <span class="st">"RNEC3_1b"</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Animal.ID =</span> <span class="fu">gsub</span>(<span class="st">'.+Stroke_(.+_.+)_[PBF].+'</span>, <span class="st">'</span><span class="sc">\\</span><span class="st">1'</span>,Animal.ID),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">timepoint =</span> <span class="fu">str_split</span>(Animal.ID, <span class="st">"_"</span>) <span class="sc">%&gt;%</span> <span class="fu">map_chr</span>(.,<span class="sc">~</span><span class="fu">ifelse</span>(<span class="fu">length</span>(.x)<span class="sc">&gt;</span><span class="dv">2</span>, .x[<span class="dv">3</span>], <span class="st">"PS3"</span>)),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">timepoint =</span> <span class="fu">ifelse</span>(timepoint <span class="sc">==</span> <span class="st">"a"</span>, <span class="st">"Baseline"</span>, timepoint),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">timepoint =</span> <span class="fu">ifelse</span>(timepoint <span class="sc">==</span> <span class="st">"b"</span>, <span class="st">"Baseline"</span>, timepoint),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Animal.ID =</span> <span class="fu">str_split</span>(Animal.ID, <span class="st">"_"</span>) <span class="sc">%&gt;%</span> <span class="fu">map_chr</span>(.,<span class="sc">~</span><span class="fu">paste</span>(.x[<span class="dv">1</span>],.x[<span class="dv">2</span>],<span class="at">sep=</span><span class="st">"."</span>)),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">stage =</span> <span class="fu">case_when</span>(<span class="fu">str_detect</span>(log_nlin_det, <span class="st">"Baseline"</span>) <span class="sc">~</span> <span class="st">"baseline"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"baseline"</span>) <span class="sc">~</span> <span class="st">"baseline"</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"PS37"</span>) <span class="sc">~</span> <span class="st">"recovery"</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"Recovery"</span>) <span class="sc">~</span> <span class="st">"recovery"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"PS30"</span>) <span class="sc">~</span> <span class="st">"recovery"</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"PS3</span><span class="sc">\\</span><span class="st">d"</span>) <span class="sc">~</span> <span class="st">"recovery"</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"PS3"</span>) <span class="sc">~</span> <span class="st">"acute"</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"RNEC3_1a_FCGStro"</span>) <span class="sc">~</span> <span class="st">"acute"</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(log_nlin_det, <span class="st">"RNEC1_1b"</span>) <span class="sc">~</span> <span class="st">"acute"</span>,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"undetected"</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 216 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (11): rigid_xfm, lsq12_nlin_xfm, overall_xfm, native_file, lsq6_file, ls...
dbl  (1): fwhm

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pipeout)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 15
  rigid_xfm      lsq12_nlin_xfm overall_xfm native_file lsq6_file lsq6_mask_file
  &lt;chr&gt;          &lt;chr&gt;          &lt;chr&gt;       &lt;chr&gt;       &lt;chr&gt;     &lt;chr&gt;         
1 FCGRat-t2-202… FCGRat-t2-202… FCGRat-t2-… /well/lerc… FCGRat-t… FCGRat-t2-202…
2 FCGRat-t2-202… FCGRat-t2-202… FCGRat-t2-… /well/lerc… FCGRat-t… FCGRat-t2-202…
3 FCGRat-t2-202… FCGRat-t2-202… FCGRat-t2-… /well/lerc… FCGRat-t… FCGRat-t2-202…
4 FCGRat-t2-202… FCGRat-t2-202… FCGRat-t2-… /well/lerc… FCGRat-t… FCGRat-t2-202…
5 FCGRat-t2-202… FCGRat-t2-202… FCGRat-t2-… /well/lerc… FCGRat-t… FCGRat-t2-202…
6 FCGRat-t2-202… FCGRat-t2-202… FCGRat-t2-… /well/lerc… FCGRat-t… FCGRat-t2-202…
# ℹ 9 more variables: nlin_file &lt;chr&gt;, nlin_mask_file &lt;chr&gt;, fwhm &lt;dbl&gt;,
#   log_nlin_det &lt;chr&gt;, log_full_det &lt;chr&gt;, label_file &lt;chr&gt;, Animal.ID &lt;chr&gt;,
#   timepoint &lt;chr&gt;, stage &lt;chr&gt;</code></pre>
</div>
</div>
<p>Reading in animal meta information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reading in the data and keeping only IDs that are unique (removing duplicates essentially)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ratinfo <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/well/lerch/users/dqp841/FCG_Rat_Stroke/analyses/Master_Data_File - info-all_clean.csv"</span>) <span class="sc">%&gt;%</span> <span class="fu">distinct</span>(<span class="st">`</span><span class="at">Animal ID</span><span class="st">`</span>, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Animal.ID =</span> <span class="st">`</span><span class="at">Animal ID</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 36 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): Animal ID, Sex, Genotype
dbl (7): #, Age (Baseline), Age (Acute), Age (Recovery), Weight (Baseline), ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># now we need to join the pipeout data frame with rat info data frame by animal ID. first, we need to see if the ID matches up across pipeout and rat info. </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pipeout<span class="sc">$</span>Animal.ID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RNEC4.1a" "RNEC4.1d" "RNEC4.1f" "RNEC3.1b" "RNEC1.1g" "RNEC1.1g"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ratinfo<span class="sc">$</span>Animal.ID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RNEC1.1p" "RNEC1.1m" "RNEC1.1n" "RNEC4.1j" "RNEC4.1i" "RNEC4.1l"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># looks the same. joining them together. setting the stage variable as a factor variable with hierarchy baseline, acute, recovery. adding full paths to log_nlin_det, log_full_det, and label_file. </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>gf <span class="ot">&lt;-</span> <span class="fu">left_join</span>(pipeout, ratinfo, <span class="at">by=</span><span class="st">"Animal.ID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">stage =</span> <span class="fu">factor</span>(stage, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"baseline"</span>, <span class="st">"acute"</span>, <span class="st">"recovery"</span>)),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">genotype =</span> <span class="fu">factor</span>(Genotype, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"XX"</span>, <span class="st">"XY"</span>, <span class="st">"XYSry"</span>, <span class="st">"XXSry"</span>)),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_nlin_det =</span> <span class="fu">paste0</span>(<span class="st">"/well/lerch/users/dqp841/FCG_Rat_Stroke/pipelines/"</span>, log_nlin_det),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_full_det =</span> <span class="fu">paste0</span>(<span class="st">"/well/lerch/users/dqp841/FCG_Rat_Stroke/pipelines/"</span>, log_full_det),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">label_file=</span><span class="fu">paste0</span>(<span class="st">"/well/lerch/users/dqp841/FCG_Rat_Stroke/pipelines/"</span>, label_file))</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co">#  getting a summary output of the genotype and stages</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>gf <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(genotype, stage) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> stage, <span class="at">values_from =</span> count, <span class="at">id_cols =</span> <span class="st">"genotype"</span>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Sum =</span> <span class="fu">rowSums</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'genotype'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   genotype [4]
  genotype baseline acute recovery   Sum
  &lt;fct&gt;       &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;dbl&gt;
1 XX              9     9        9    27
2 XY              9     9        9    27
3 XYSry          10    10       10    30
4 XXSry           8     8        8    24</code></pre>
</div>
</div>
<p>Reading in the consensus/averaged segmented image generated after nonlinear transformation round 3 (nlin-3). This will be used downstream as a mask to indicate which voxels in the images can be used to make linear models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mask <span class="ot">&lt;-</span> <span class="st">"/well/lerch/users/dqp841/FCG_Rat_Stroke/pipelines/FCGRat-t2-2024-10-03_nlin/FCGRat-t2-2024-10-03-nlin-3/FCGRat-t2-2024-10-03-nlin-3_voted.mnc"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="analyses" class="level2">
<h2 class="anchored" data-anchor-id="analyses">Analyses</h2>
<p>In the following examples, different types of models are fitted to answer some very specific questions.</p>
<section id="simple-case-vs_genotype-model" class="level3">
<h3 class="anchored" data-anchor-id="simple-case-vs_genotype-model">Simple case: vs_genotype model</h3>
<p>Here, the <a href="https://rdrr.io/github/Mouse-Imaging-Centre/RMINC/man/mincLm.html">mincLm function</a> from the RMINC package is used. This function allows you to fit a linear model across all voxels in the data.</p>
<p>The model is addressing this question: which voxels show statistically significant volumetric differences between the genotypes at the baseline time point?</p>
<p>Notice the mask imported earlier is used here to help mincLm determine which voxels in the images that can be included for linear modeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note that this is using the log_full_determinants. total brain volume are not accounted for in this model. to do that, you'd use relative determinants. </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>vs_genotype <span class="ot">&lt;-</span> <span class="fu">mincLm</span>(log_full_det <span class="sc">~</span> genotype, gf <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(stage <span class="sc">==</span> <span class="st">"baseline"</span>), <span class="at">mask=</span>mask)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Method: lm
Number of volumes: 36
Volume sizes: 67 131 85
N: 36 P: 4
In slice 
 0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 
Done</code></pre>
</div>
</div>
<p>I want to explore the outputs of vs_genotype and build up my understanding of what’s available for visualization purposes from there.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># what's in vs_genotype </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vs_genotype)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "F-statistic"          "R-squared"            "beta-(Intercept)"    
 [4] "beta-genotypeXY"      "beta-genotypeXYSry"   "beta-genotypeXXSry"  
 [7] "tvalue-(Intercept)"   "tvalue-genotypeXY"    "tvalue-genotypeXYSry"
[10] "tvalue-genotypeXXSry" "logLik"              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vs_genotype)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     F-statistic R-squared beta-(Intercept) beta-genotypeXY beta-genotypeXYSry
[1,]           0         0                0               0                  0
[2,]           0         0                0               0                  0
[3,]           0         0                0               0                  0
[4,]           0         0                0               0                  0
[5,]           0         0                0               0                  0
[6,]           0         0                0               0                  0
     beta-genotypeXXSry tvalue-(Intercept) tvalue-genotypeXY
[1,]                  0                  0                 0
[2,]                  0                  0                 0
[3,]                  0                  0                 0
[4,]                  0                  0                 0
[5,]                  0                  0                 0
[6,]                  0                  0                 0
     tvalue-genotypeXYSry tvalue-genotypeXXSry logLik
[1,]                    0                    0      0
[2,]                    0                    0      0
[3,]                    0                    0      0
[4,]                    0                    0      0
[5,]                    0                    0      0
[6,]                    0                    0      0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(vs_genotype)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 746045     11</code></pre>
</div>
</div>
<p>So the results from mincLm seems to include the beta coefficients (differences) in log_full_determinants between XX and the other genotypes at baseline (XX is not present, so it’s serving as the reference variable for all comparisons), and t-statistics associated with the difference between XX and the other genotypes.</p>
<p>If you want to see whether XY is different from the other genotypes, for example, you would need to refactor the data. Sample code below (this code is not run).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>gf <span class="sc">%&gt;%</span> genotype <span class="ot">=</span> <span class="fu">factor</span>(Genotype, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"XY"</span>, <span class="st">"XX"</span>, <span class="st">"XYSry"</span>, <span class="st">"XXSry"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are 746,045 voxels where these statistics are available. That’s too many comparisons, and we run the risk of having voxels that are not actually different between the groups deemed significant (false positives). Multiple comparison adjustments need to be done.</p>
<p>This is where <a href="https://rdrr.io/github/Mouse-Imaging-Centre/RMINC/man/mincFDR.html">mincFDR</a> comes in. mincFDR takes a mincLm object as an input, and then (I think) it: 1) converts the t-values in mincLm to p-values and 2) applies the <code>p.adjust</code> function to all voxels, taking into account how many voxels there are in total.</p>
<p>Let’s apply mincFDR to our simple model and see its outputs. I’m calling it vs_genotype_qvals because after FDR adjustments, p-values are called q-values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>vs_genotype_qvals <span class="ot">&lt;-</span> <span class="fu">mincFDR</span>(vs_genotype)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computing FDR threshold for all columns
  Computing threshold for  F-statistic 
  Computing threshold for  tvalue-(Intercept) 
  Computing threshold for  tvalue-genotypeXY 
  Computing threshold for  tvalue-genotypeXYSry 
  Computing threshold for  tvalue-genotypeXXSry </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vs_genotype_qvals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     qvalue-F-statistic qvalue-tvalue-(Intercept) qvalue-tvalue-genotypeXY
[1,]                  1                         1                        1
[2,]                  1                         1                        1
[3,]                  1                         1                        1
[4,]                  1                         1                        1
[5,]                  1                         1                        1
[6,]                  1                         1                        1
     qvalue-tvalue-genotypeXYSry qvalue-tvalue-genotypeXXSry
[1,]                           1                           1
[2,]                           1                           1
[3,]                           1                           1
[4,]                           1                           1
[5,]                           1                           1
[6,]                           1                           1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(vs_genotype_qvals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 746045      5</code></pre>
</div>
</div>
<p>So you get a matrix with the same number of voxels (rows) as your input model and some columns labeled <code>qvalue-tvalue-genotype</code>. I suspect that these are the going to be the adjusted p-values (or q-values) you’ll want to visualize on your atlases!</p>
<p>Let’s just double check that’s the case. I’m checking the range of these q-value columns. If they’re all between 0 and 1, that would mean they are in fact adjusted p-values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># apply the function (range) to all columns in vs_genotype_qvals </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(vs_genotype_qvals), <span class="cf">function</span>(x) <span class="fu">range</span>(vs_genotype_qvals[,x]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]         [,2]      [,3]         [,4]        [,5]
[1,] 0.0006884425 2.438496e-07 0.0061084 9.327254e-05 0.006208024
[2,] 1.0000000000 1.000000e+00 1.0000000 1.000000e+00 1.000000000</code></pre>
</div>
</div>
<p>Nice! They’re all 0 - 1. That means they’re all adjusted p-values, and there is a way to visualize these on your atlases.</p>
</section>
</section>
<section id="visualizations" class="level2">
<h2 class="anchored" data-anchor-id="visualizations">Visualizations</h2>
<p>To do our visualizations, we need a couple more things. First, a template image so the statistics visualizations can be laid on top of it. Here we’re using the average nlin-3 image from the pipeline.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>nlin <span class="ot">&lt;-</span> <span class="fu">mincArray</span>(<span class="fu">mincGetVolume</span>(<span class="st">"/well/lerch/users/dqp841/FCG_Rat_Stroke/pipelines/FCGRat-t2-2024-10-03_nlin/FCGRat-t2-2024-10-03-nlin-3.mnc"</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(nlin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  85 131  67</code></pre>
</div>
</div>
<p>Then, the atlas labels of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using the 'mask' file again because it's actually the labelled atlas. </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>labelVol <span class="ot">&lt;-</span> <span class="fu">mincArray</span>(<span class="fu">mincGetVolume</span>(mask))</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(labelVol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  85 131  67</code></pre>
</div>
</div>
<p>Notice when I print the dimensions of nlin and labelVol, they are exactly the same. That’s because nlin is the nlin-3 image, and labelVol is the labels of the nlin-3 image (nlin-3_voted).</p>
<p>Both files have 85 slices in the x-axis, 131 slices in the y-axis, and 67 slices in the z-axis.</p>
<p>Let’s look at an example slice from these data matrices to see what information they’re storing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pull a sample of the matrix representing voxels in slice 30 of z-axis in nlin and labelVol</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>nlin[, ,<span class="dv">30</span> ][<span class="dv">35</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]   75.00039   93.25433  126.19213  167.79124  203.70927  221.99425
  [7]  277.62530  472.76857  981.20899 1431.31753 1611.21815 1604.14009
 [13] 1378.85299 1197.64852 1150.36834 1136.08805 1074.49654 1026.50235
 [19] 1050.93406 1037.64718 1036.77795 1168.96376 1372.70625 1338.99235
 [25]  945.19782  782.15416  816.70626  794.91329  866.19057  873.33071
 [31]  800.22183  765.54556  851.78610  973.07543 1016.59928 1039.19939
 [37] 1044.16644  989.55986  983.94087  985.46203  904.62317  829.18599
 [43]  797.14847  777.87007  751.04796  730.83825  735.61904  740.74132
 [49]  757.10157  751.88615  716.68213  717.05466  715.12993  727.42340
 [55]  749.46471  710.93897  838.46818  928.96175  868.42574  861.40977
 [61]  840.20665  840.88962  848.68169  839.02697  828.31675  831.07968
 [67]  814.65734  826.67141  833.50112  780.81926  807.79660  881.12278
 [73]  975.62105  972.70290  955.75282  999.27666 1022.46661 1055.68381
 [79] 1064.81078 1067.97728 1076.60754 1084.08917 1078.43914 1085.17571
 [85] 1079.71195 1092.71943 1156.51508 1161.32691 1090.39112  970.74713
 [91]  888.91485  941.00687 1075.98666 1177.59403 1177.06628 1115.81625
 [97]  869.32602  508.22094  289.85667  218.88984  196.69330  207.12412
[103]  217.05824  235.71575  254.12490  275.94891  265.26974  252.44852
[109]  213.79861  211.87387  252.69688  269.02608  292.27812  394.59950
[115]  490.77415  521.97348  566.58387  563.13797  528.36857  500.33574
[121]  475.03479  482.54746  452.93138  412.41882  376.87331  362.15841
[127]  335.18107  318.94501  273.09286  213.98487  126.03691</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>labelVol[, ,<span class="dv">30</span>][<span class="dv">35</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  29  29  29
 [19]  29  29  29   0   0   0   7 193   7 189 189 189 189   7 189 189 189 189
 [37] 208 208 208 208 208 208 208 208 208 208 208 208 208 208 208 208 208 156
 [55] 156 208 156 156 156 156 156 156 156 156 156 156 156 156 156 156  45  45
 [73]  78  78  50 243  50  50  50  50  50  50  47  47  47  47  95  41  41  41
 [91]  41  41  41  41  41  41   0   0   0   0   0   0   0   0   0   0   0   0
[109]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[127]   0   0   0   0   0</code></pre>
</div>
</div>
<p>I’ve pulled out 129 values each from <code>nlin</code> and <code>labelVol</code>. Each of these values are information contained within a subset of voxels at slice 30 in the z-axis.</p>
<p>In <code>nlin</code>, the voxels are decimal numbers representing image intensity.</p>
<p>In <code>labelVol</code>, the voxels are whole numbers representing an atlas label (i.e.&nbsp;1 is Hippocampus. I’m just making up the numbers and their associations. Actual associations are likely different).</p>
<p>With that in mind, I’m gonna annotate the following visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># start a sliceSeries, with 1 row and 5 columns. use slices from the z-axis (default), and plot 5 slices (5 columns) from slices 30 through 90. </span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sliceSeries</span>(<span class="at">nrow=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">5</span>, <span class="at">begin=</span><span class="dv">30</span>, <span class="at">end=</span><span class="dv">90</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># overlay the anatomy image. in our case, is the nlin-3 image. plot voxels that are between 700 to 1400 in their image intensities. </span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anatomy</span>(nlin, <span class="at">low=</span><span class="dv">700</span>, <span class="at">high=</span><span class="dv">1400</span>) <span class="sc">%&gt;%</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># overlay the statistics. see explanation below the figure that will be generated</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">overlay</span>(<span class="sc">-</span><span class="fu">log10</span>(<span class="fu">mincArray</span>(vs_genotype_qvals, <span class="st">"qvalue-tvalue-genotypeXXSry"</span>)) <span class="sc">*</span> (labelVol<span class="sc">&gt;</span><span class="fl">0.5</span>) <span class="sc">*</span> <span class="fu">sign</span>(<span class="fu">mincArray</span>(vs_genotype, <span class="st">"tvalue-genotypeXXSry"</span>)), <span class="at">low=</span><span class="fl">0.1</span>, <span class="at">high=</span><span class="dv">2</span>, <span class="at">symmetric=</span>T) <span class="sc">%&gt;%</span> </span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co"># add a title</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addtitle</span>(<span class="st">"XXSry abs"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="co"># add a legend </span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">legend</span>(<span class="st">"-log10 q-value"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="co"># draw the figure! </span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">draw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.svg" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-statistics-overlay" class="level2">
<h2 class="anchored" data-anchor-id="the-statistics-overlay">The statistics overlay</h2>
<p>As a reminder, this was our statistics overlay code for the visualization.</p>
<p><code>overlay(-log10(mincArray(vs_genotype_qvals, "qvalue-tvalue-genotypeXXSry")) * (labelVol&gt;0.5) * sign(mincArray(vs_genotype, "tvalue-genotypeXXSry")), low=0.1, high=2, symmetric=T)</code></p>
<p>To explain how this works , let’s break down how it’s calculated first. I’m still pulling a sample from slice 30 of z-dimension to be consistent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1: calculate -log10 of q-values at every voxels. log10 is multipled by negative 1 because log10 gives negative values for anything less than 1. Negative q-values don't make sense. Applying log10 to the q-value is just scaling them up to make visualization easier (seeing the difference between 0 and 2 is easier than 0 and 1) </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>log10_q <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">log10</span>(<span class="fu">mincArray</span>(vs_genotype_qvals, <span class="st">"qvalue-tvalue-genotypeXXSry"</span>))[, ,<span class="dv">30</span>][<span class="dv">35</span>,]</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>log10_q </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  [7] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [13] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [19] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [25] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [31] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [37] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [43] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [49] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [55] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [61] 0.20750872 0.35157189 0.44689661 0.39531659 0.29839121 0.28133185
 [67] 0.21447423 0.07332705 0.13295974 0.25733193 0.47530662 0.61956803
 [73] 0.74616107 0.54277334 0.25480405 0.05685436 0.00000000 0.00000000
 [79] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [85] 0.09534905 0.44918051 0.78955389 0.86610506 0.90096597 0.76349428
 [91] 0.40968016 0.23513449 0.01712954 0.00000000 0.00000000 0.00000000
 [97] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[103] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[109] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[115] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[121] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[127] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2: identify if a voxel is actually inside a region of interest/inside the brain using the following code. in R, TRUE is coded as 1 and FALSE is coded as 0. so imagine the output is a matrix of TRUE/FALSE is also read as a 1/0 matrix. if a voxel is inside the brain/associated with a brain region, it would have an atlas label &gt; 0. hence why this works. </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>label_in_brain <span class="ot">&lt;-</span> labelVol[, ,<span class="dv">30</span>][<span class="dv">35</span>,]<span class="sc">&gt;</span><span class="fl">0.5</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>label_in_brain </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE
 [25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [49]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [73]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 3: identify the signs associated with t-values in the voxels. negative means it's lesser volume in the XXSry genotype compared to XX. positive means it's greater in volume for XXSry genotype compared to XX. </span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>tvals_sign <span class="ot">&lt;-</span> <span class="fu">sign</span>(<span class="fu">mincArray</span>(vs_genotype, <span class="st">"tvalue-genotypeXXSry"</span>)[, ,<span class="dv">30</span>][<span class="dv">35</span>,])</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>tvals_sign</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  0  0  0  1
 [26]  1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1
 [51]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [76]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0
[101]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
[126]  0  0  0  0  0  0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># notice these vectors have the same dimension. we're referring to the same voxels across all of these vectors.</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(log10_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(label_in_brain)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(tvals_sign)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 4: multiply all three vectors together. these are the values plotted on your visualization. </span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>sample_qvals_on_map <span class="ot">&lt;-</span> log10_q <span class="sc">*</span> label_in_brain <span class="sc">*</span> tvals_sign</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>sample_qvals_on_map</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  [7] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [13] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [19] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [25] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [31] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [37] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [43] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [49] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [55] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [61] 0.20750872 0.35157189 0.44689661 0.39531659 0.29839121 0.28133185
 [67] 0.21447423 0.07332705 0.13295974 0.25733193 0.47530662 0.61956803
 [73] 0.74616107 0.54277334 0.25480405 0.05685436 0.00000000 0.00000000
 [79] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 [85] 0.09534905 0.44918051 0.78955389 0.86610506 0.90096597 0.76349428
 [91] 0.40968016 0.23513449 0.01712954 0.00000000 0.00000000 0.00000000
 [97] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[103] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[109] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[115] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[121] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[127] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000</code></pre>
</div>
</div>
<p>Notice that the range of these sample q-values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(sample_qvals_on_map)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000000 0.900966</code></pre>
</div>
</div>
<p>In this case, they’re from 0 to 0.91. Notice in the code, we had this bit `<code>low=0.1, high=2, symmetric=T)`</code> . Here, any voxel where the -log10 q-value is below 0.1 is not plotted, and anything beyond 2 is not plotted (assuming the smallest raw q-value is 0.01). If I increase the low threshold to 0.7</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sliceSeries</span>(<span class="at">nrow=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">5</span>, <span class="at">begin=</span><span class="dv">30</span>, <span class="at">end=</span><span class="dv">90</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anatomy</span>(nlin, <span class="at">low=</span><span class="dv">700</span>, <span class="at">high=</span><span class="dv">1400</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">overlay</span>(<span class="sc">-</span><span class="fu">log10</span>(<span class="fu">mincArray</span>(vs_genotype_qvals, <span class="st">"qvalue-tvalue-genotypeXXSry"</span>)) <span class="sc">*</span> (labelVol<span class="sc">&gt;</span><span class="fl">0.5</span>) <span class="sc">*</span> <span class="fu">sign</span>(<span class="fu">mincArray</span>(vs_genotype, <span class="st">"tvalue-genotypeXXSry"</span>)), <span class="at">low=</span><span class="fl">0.7</span>, <span class="at">high=</span><span class="dv">2</span>, <span class="at">symmetric=</span>T) <span class="sc">%&gt;%</span> <span class="fu">legend</span>(<span class="st">"-log10 q-value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addtitle</span>(<span class="st">"XXSry abs"</span>) <span class="sc">%&gt;%</span> <span class="fu">draw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.svg" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Why do we want to have all of these modifications to the original q-values? If you play around with the code and take out <code>(labelVol&gt;0.5) * sign(mincArray(vs_genotype, "tvalue-genotypeXXSry")</code>, your display will look exactly the same given the slices you’ve chosen.</p>
<p>But, if you choose different slices (say instead of between 30 - 90, you pick somewhere closer to beginning or final slices i.e.&nbsp;110 - 131), where the data is noisier, I would suspect you’ll get more inaccurate display of your stats. Just play around and see if this is true!</p>
<p>I hope this will help you have more flexibility in using RMINC to visualize your results.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/users\.ox\.ac\.uk\/~ndcn0890\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="jasonlerch/blogComments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>